// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ6lV9mL6HLqs15-331lI5qfcEyg5Kh1A',
    appId: '1:198513213548:web:742845fae00e4623d59849',
    messagingSenderId: '198513213548',
    projectId: 'personal-blog-c9334',
    authDomain: 'personal-blog-c9334.firebaseapp.com',
    storageBucket: 'personal-blog-c9334.appspot.com',
    measurementId: 'G-8HMQPTY1RF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeQKAJEx0AHdqtOD3QB35r6SC35ERrj5w',
    appId: '1:198513213548:android:e47e2b1bb9c64fb5d59849',
    messagingSenderId: '198513213548',
    projectId: 'personal-blog-c9334',
    storageBucket: 'personal-blog-c9334.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAES-Rc-tDDTq0JSPH-ANswjqfBtztXYn4',
    appId: '1:198513213548:ios:626a8530620de46bd59849',
    messagingSenderId: '198513213548',
    projectId: 'personal-blog-c9334',
    storageBucket: 'personal-blog-c9334.appspot.com',
    iosClientId: '198513213548-78oof8n2grid3u0he15fr1lpg8md09cu.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalBlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAES-Rc-tDDTq0JSPH-ANswjqfBtztXYn4',
    appId: '1:198513213548:ios:626a8530620de46bd59849',
    messagingSenderId: '198513213548',
    projectId: 'personal-blog-c9334',
    storageBucket: 'personal-blog-c9334.appspot.com',
    iosClientId: '198513213548-78oof8n2grid3u0he15fr1lpg8md09cu.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalBlog',
  );
}
